version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: homecare

  adminer:
    image: adminer
    restart: always
    ports:
      - "3308:3306"